name = "embed-builder-bot"
main = "./src/server.js"
type = "javascript"
compatibility_date="2022-02-26"
node_compat = true

[[rules]]
type = "ESModule"
globs = [ "**/*.js" ]

[env.dev]
workers_dev = true
vars_files = ".dev.env"